"""schema inicial

Revision ID: 16d8fa049020
Revises: 
Create Date: 2026-07-31 00:21:04.880909

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '16d8fa049020'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admins',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('senha_hash', sa.String(length=255), nullable=False),
    sa.Column('criado_em', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('admins', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_admins_email'), ['email'], unique=True)

    op.create_table('categorias',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=60), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome')
    )
    op.create_table('clientes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('senha_hash', sa.String(length=255), nullable=False),
    sa.Column('status', sa.Enum('ativo', 'bloqueado', name='statuscliente'), nullable=False),
    sa.Column('criado_em', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('clientes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_clientes_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_clientes_status'), ['status'], unique=False)

    op.create_table('planos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=80), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('preco_centavos', sa.Integer(), nullable=False),
    sa.Column('duracao_dias', sa.Integer(), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('mp_plan_id', sa.String(length=120), nullable=True),
    sa.Column('criado_em', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('planos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_planos_ativo'), ['ativo'], unique=False)

    op.create_table('assinaturas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=False),
    sa.Column('plano_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('pendente', 'ativa', 'atrasada', 'cancelada', name='statusassinatura'), nullable=False),
    sa.Column('mp_subscription_id', sa.String(length=120), nullable=True),
    sa.Column('data_inicio', sa.DateTime(), nullable=True),
    sa.Column('data_expiracao', sa.DateTime(), nullable=True),
    sa.Column('data_proximo_pagamento', sa.DateTime(), nullable=True),
    sa.Column('criado_em', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['plano_id'], ['planos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('assinaturas', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_assinaturas_cliente_id'), ['cliente_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_assinaturas_data_expiracao'), ['data_expiracao'], unique=False)
        batch_op.create_index(batch_op.f('ix_assinaturas_mp_subscription_id'), ['mp_subscription_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_assinaturas_status'), ['status'], unique=False)

    op.create_table('series',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(length=200), nullable=False),
    sa.Column('sinopse', sa.Text(), nullable=True),
    sa.Column('categoria_id', sa.Integer(), nullable=True),
    sa.Column('capa_url', sa.String(length=500), nullable=True),
    sa.Column('banner_url', sa.String(length=500), nullable=True),
    sa.Column('ano', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('rascunho', 'publicado', name='statusserie'), nullable=False),
    sa.Column('criado_em', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['categoria_id'], ['categorias.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('series', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_series_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_series_titulo'), ['titulo'], unique=False)

    op.create_table('importacoes_playlist',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('serie_id', sa.Integer(), nullable=False),
    sa.Column('playlist_url', sa.String(length=500), nullable=False),
    sa.Column('total_encontrados', sa.Integer(), nullable=False),
    sa.Column('total_importados', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('processando', 'concluida', 'erro', name='statusimportacao'), nullable=False),
    sa.Column('criado_em', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['serie_id'], ['series.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('importacoes_playlist', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_importacoes_playlist_serie_id'), ['serie_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_importacoes_playlist_status'), ['status'], unique=False)

    op.create_table('minha_lista',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=False),
    sa.Column('serie_id', sa.Integer(), nullable=False),
    sa.Column('criado_em', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['serie_id'], ['series.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cliente_id', 'serie_id', name='uq_minha_lista_cliente_serie')
    )
    with op.batch_alter_table('minha_lista', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_minha_lista_cliente_id'), ['cliente_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_minha_lista_serie_id'), ['serie_id'], unique=False)

    op.create_table('pagamentos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('assinatura_id', sa.Integer(), nullable=False),
    sa.Column('mp_payment_id', sa.String(length=120), nullable=True),
    sa.Column('valor_centavos', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('pendente', 'aprovado', 'rejeitado', 'estornado', name='statuspagamento'), nullable=False),
    sa.Column('criado_em', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['assinatura_id'], ['assinaturas.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('pagamentos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_pagamentos_assinatura_id'), ['assinatura_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_pagamentos_mp_payment_id'), ['mp_payment_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_pagamentos_status'), ['status'], unique=False)

    op.create_table('temporadas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('serie_id', sa.Integer(), nullable=False),
    sa.Column('numero', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(length=120), nullable=True),
    sa.ForeignKeyConstraint(['serie_id'], ['series.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('serie_id', 'numero', name='uq_temporada_serie_numero')
    )
    with op.batch_alter_table('temporadas', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_temporadas_serie_id'), ['serie_id'], unique=False)

    op.create_table('episodios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('serie_id', sa.Integer(), nullable=False),
    sa.Column('temporada_id', sa.Integer(), nullable=True),
    sa.Column('numero', sa.Integer(), nullable=True),
    sa.Column('titulo', sa.String(length=200), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('thumbnail_url', sa.String(length=500), nullable=True),
    sa.Column('duracao_segundos', sa.Integer(), nullable=True),
    sa.Column('ordem', sa.Integer(), nullable=False),
    sa.Column('fonte', sa.Enum('youtube_embed', 'youtube_baixado', 'local', 'panda', name='fonteepisodio'), nullable=False),
    sa.Column('youtube_video_id', sa.String(length=32), nullable=True),
    sa.Column('arquivo_local_path', sa.String(length=500), nullable=True),
    sa.Column('status_processamento', sa.Enum('pronto', 'pendente', 'baixando', 'erro', name='statusprocessamento'), nullable=False),
    sa.Column('criado_em', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['serie_id'], ['series.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['temporada_id'], ['temporadas.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('episodios', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_episodios_ordem'), ['ordem'], unique=False)
        batch_op.create_index(batch_op.f('ix_episodios_serie_id'), ['serie_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_episodios_status_processamento'), ['status_processamento'], unique=False)

    op.create_table('progresso',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=False),
    sa.Column('episodio_id', sa.Integer(), nullable=False),
    sa.Column('segundos_assistidos', sa.Integer(), nullable=False),
    sa.Column('concluido', sa.Boolean(), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['episodio_id'], ['episodios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cliente_id', 'episodio_id', name='uq_progresso_cliente_episodio')
    )
    with op.batch_alter_table('progresso', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_progresso_cliente_id'), ['cliente_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_progresso_episodio_id'), ['episodio_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('progresso', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_progresso_episodio_id'))
        batch_op.drop_index(batch_op.f('ix_progresso_cliente_id'))

    op.drop_table('progresso')
    with op.batch_alter_table('episodios', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_episodios_status_processamento'))
        batch_op.drop_index(batch_op.f('ix_episodios_serie_id'))
        batch_op.drop_index(batch_op.f('ix_episodios_ordem'))

    op.drop_table('episodios')
    with op.batch_alter_table('temporadas', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_temporadas_serie_id'))

    op.drop_table('temporadas')
    with op.batch_alter_table('pagamentos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pagamentos_status'))
        batch_op.drop_index(batch_op.f('ix_pagamentos_mp_payment_id'))
        batch_op.drop_index(batch_op.f('ix_pagamentos_assinatura_id'))

    op.drop_table('pagamentos')
    with op.batch_alter_table('minha_lista', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_minha_lista_serie_id'))
        batch_op.drop_index(batch_op.f('ix_minha_lista_cliente_id'))

    op.drop_table('minha_lista')
    with op.batch_alter_table('importacoes_playlist', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_importacoes_playlist_status'))
        batch_op.drop_index(batch_op.f('ix_importacoes_playlist_serie_id'))

    op.drop_table('importacoes_playlist')
    with op.batch_alter_table('series', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_series_titulo'))
        batch_op.drop_index(batch_op.f('ix_series_status'))

    op.drop_table('series')
    with op.batch_alter_table('assinaturas', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_assinaturas_status'))
        batch_op.drop_index(batch_op.f('ix_assinaturas_mp_subscription_id'))
        batch_op.drop_index(batch_op.f('ix_assinaturas_data_expiracao'))
        batch_op.drop_index(batch_op.f('ix_assinaturas_cliente_id'))

    op.drop_table('assinaturas')
    with op.batch_alter_table('planos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_planos_ativo'))

    op.drop_table('planos')
    with op.batch_alter_table('clientes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_clientes_status'))
        batch_op.drop_index(batch_op.f('ix_clientes_email'))

    op.drop_table('clientes')
    op.drop_table('categorias')
    with op.batch_alter_table('admins', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_admins_email'))

    op.drop_table('admins')
    # ### end Alembic commands ###
