"""unique constraint em mp_payment_id

Revision ID: 614563e5dabc
Revises: 0da909f82a1c
Create Date: 2026-08-12 20:47:15.723778

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '614563e5dabc'
down_revision: Union[str, None] = '0da909f82a1c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pagamentos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pagamentos_mp_payment_id'))
        batch_op.create_index(batch_op.f('ix_pagamentos_mp_payment_id'), ['mp_payment_id'], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pagamentos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pagamentos_mp_payment_id'))
        batch_op.create_index(batch_op.f('ix_pagamentos_mp_payment_id'), ['mp_payment_id'], unique=False)

    # ### end Alembic commands ###
